name: Test Release

on: pull_request

jobs:
  test_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 18
      - env:
          CI: true
        run: "yarn install"
      - env:
          CI: true
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
          GITHUB_HEAD_REF: $GITHUB_HEAD_REF
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > /home/runner/work/_temp/.npmrc
          npx semantic-release --dry-run --debug -b $GITHUB_HEAD_REF

      - name: Snyk Test
        env:
          CI: true
        run: npx --yes snyk test --token "${{ secrets.SNYK_TOKEN }}"
