name: Test Release

on: pull_request

jobs:
  test_publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - env:
          CI: true
        run: "yarn install"
      - env:
          CI: true
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
          GITHUB_HEAD_REF: $GITHUB_HEAD_REF
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > /home/runner/work/_temp/.npmrc
          npx semantic-release --dry-run --debug -b $GITHUB_HEAD_REF

    test_snyk:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [18.x]

      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: "yarn"
        - run: yarn install
        - run: yarn global add snyk
        - run: snyk auth ${{ secrets.SNYK_TOKEN }}
        - run: snyk monitor

        - name: install snyk-to-html
          run: |
            yarn global add snyk-to-html
            snyk test --json | snyk-to-html -o result.html
            mkdir downloads
            cp -v /home/runner/work/java-goof/java-goof/*.html /home/runner/work/java-goof/java-goof/downloads

        - name: Use the Upload Artifact GitHub Action
          uses: actions/upload-artifact@v3
          with:
            name: results
            path: downloads
